{% set name = "pdb2pqr" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05b5c464022a3ad11c9597c6fc7f70c56061c4669b1497a51958da90d959152f

build:
  noarch: python
  number: 0
  entry_points:
    - pdb2pqr30=pdb2pqr.main:main
    - dx2cube=pdb2pqr.main:dx_to_cube
    - psize=pdb2pqr.psize:main
    - inputgen=pdb2pqr.inputgen:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - mmcif_pdbx >=1.1.2
    - pandas >=1.0
    - propka >=3.5
    - python >={{ python_min }}
    - numpy
    - requests
    - setuptools  # for pkg_resources

test:
  imports:
    - pdb2pqr
    - pdb2pqr.hydrogens
    - pdb2pqr.ligand
  commands:
    - pdb2pqr30 --help
    - dx2cube --help
    - inputgen --help
  requires:
    - pytest
    - testfixtures
    - python {{ python_min }}

about:
  home: http://www.poissonboltzmann.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automates many of the common tasks of preparing structures for continuum solvation calculations as well as many other types of biomolecular structure modeling, analysis, and simulation.
  doc_url: https://pdb2pqr.readthedocs.io/en/latest/
  dev_url: https://github.com/Electrostatics/pdb2pqr

extra:
  recipe-maintainers:
    - tsenapathi
    - sobolevnrm
